spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobhunter
    username: root
    password: root1234@zz
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true # config pagination start page from 1 instead of 0

# config jwt
khang:
  jwt:
    base64-secret: sw4SKUTefsiUWl+HDM91jywfWxg2HIAyBNiaMkokHCv75q0MCHZ9hHL78B04Pe15Z0jSYbLpkyhHlPRBVDsQeg==
    # expriation: 1 day (seconds)
    token-validity-in-seconds: 86400
